format = """
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$c\
$dart\
$deno\
$gleam\
$golang\
$haskell\
$helm\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$solidity\
$terraform\
$typst\
$vlang\
$zig\
$buf\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$sudo\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character\
"""

add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[line_break]
disabled = true

[directory]
truncation_length = 8

