set number
set laststatus=2

call plug#begin('~/.vim/plugged')

Plug 'chrisbra/colorizer'
Plug 'itchyny/lightline.vim'

call plug#end()

let g:colorizer_auto_color = 1

let g:lightline = {'colorscheme': 'wombat'}
